version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv virtualenvironment
            . virtualenvironment/Scripts/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "virtualenvironment"
      - run:
          name: Running tests
          command: |
            . virtualenvironment/bin/activate
            python test_queries.py
      - store_artifacts:
          path: test-reports/
          destination: python_app